[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "wheel",
]

[tool]
[tool.pytest.ini_options]
addopts = "--color=yes -vv"
console_output_style = "progress"
testpaths = [
  "tests",
]

[tool.pylint.miscellaneous]
output-format = "colorized"
